CONFIG_BOARD_FLASH_SIZE := 2

CONFIG_BL_IOT_FW_AP := 1
CONFIG_ENABLE_PSM_RAM := 1
CONFIG_ENABLE_VFS_ROMFS := 1
CONFIG_EASYFLASH_ENABLE := 1
CONFIG_BL602_USE_ROM_DRIVER := 1
CONFIG_FREERTOS_TICKLESS_MODE := 0

CONFIG_SYS_APP_TASK_STACK_SIZE := 4096
CONFIG_SYS_APP_TASK_PRIORITY := 15
CONFIG_SYS_VFS_ENABLE := 1
CONFIG_SYS_AOS_CLI_ENABLE := 1
CONFIG_SYS_AOS_LOOP_ENABLE := 1
CONFIG_SYS_BLOG_ENABLE := 1
CONFIG_SYS_DMA_ENABLE := 1

CONFIG_BT := 1
CONFIG_BT_CENTRAL := 1
CONFIG_BT_OBSERVER := 1
CONFIG_BT_PERIPHERAL := 1
CONFIG_BT_STACK_CLI := 1
CONFIG_BLE_STACK_DBG_PRINT := 1
CONF_ENABLE_COREDUMP := 1

CONFIG_MBEDTLS_AES_USE_HW := 1
CONFIG_MBEDTLS_BIGNUM_USE_HW := 1
CONFIG_MBEDTLS_ECC_USE_HW := 1
CONFIG_MBEDTLS_SHA1_USE_HW := 1
CONFIG_MBEDTLS_SHA256_USE_HW := 1

LOG_ENABLED_COMPONENTS := blog_testc hosal loopset looprt bloop
